name: 'Package Info'
description: 'Extract package name, version, and metadata from package.json'
author: 'SylphxAI'

branding:
  icon: 'info'
  color: 'blue'

inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'

outputs:
  name:
    description: 'Package name'
    value: ${{ steps.info.outputs.name }}
  version:
    description: 'Package version'
    value: ${{ steps.info.outputs.version }}
  private:
    description: 'Is private package'
    value: ${{ steps.info.outputs.private }}
  is_monorepo:
    description: 'Is monorepo'
    value: ${{ steps.info.outputs.is_monorepo }}
  workspaces:
    description: 'Workspace patterns (JSON array)'
    value: ${{ steps.info.outputs.workspaces }}
  packages:
    description: 'All packages info (JSON array for monorepo)'
    value: ${{ steps.info.outputs.packages }}

runs:
  using: 'composite'
  steps:
    - name: Extract package info
      id: info
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Single package info
        NAME=$(jq -r '.name // empty' package.json)
        VERSION=$(jq -r '.version // empty' package.json)
        PRIVATE=$(jq -r '.private // false' package.json)
        WORKSPACES=$(jq -c '.workspaces // []' package.json)

        echo "name=$NAME" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "private=$PRIVATE" >> $GITHUB_OUTPUT
        echo "workspaces=$WORKSPACES" >> $GITHUB_OUTPUT

        # Check monorepo
        if [ "$WORKSPACES" != "[]" ]; then
          echo "is_monorepo=true" >> $GITHUB_OUTPUT

          # Collect all package info
          PACKAGES="[]"
          for pattern in $(echo "$WORKSPACES" | jq -r '.[]'); do
            for pkg_dir in $pattern; do
              [ -f "$pkg_dir/package.json" ] || continue
              PKG_INFO=$(jq -c '{
                name: .name,
                version: .version,
                private: (.private // false),
                path: "'"$pkg_dir"'"
              }' "$pkg_dir/package.json")
              PACKAGES=$(echo "$PACKAGES" | jq -c ". + [$PKG_INFO]")
            done
          done
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT
        else
          echo "is_monorepo=false" >> $GITHUB_OUTPUT
          echo "packages=[]" >> $GITHUB_OUTPUT
        fi

        # Summary
        echo "📦 Package: $NAME@$VERSION"
        echo "   Private: $PRIVATE"
        echo "   Monorepo: $([ "$WORKSPACES" != "[]" ] && echo "yes" || echo "no")"
