name: 'Slack Notify'
description: 'Send Slack notification'
author: 'SylphxAI'

branding:
  icon: 'message-circle'
  color: 'purple'

inputs:
  webhook:
    description: 'Slack webhook URL'
    required: true
  message:
    description: 'Message to send (supports Slack mrkdwn format)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send Slack notification
      shell: bash
      env:
        WEBHOOK: ${{ inputs.webhook }}
        MESSAGE: ${{ inputs.message }}
      run: |
        curl -s -X POST "$WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "$(jq -n --arg text "$MESSAGE" '{text: $text}')"
