name: 'Publish to NPM'
description: 'Publish packages to npm using bump with Slack notifications'
author: 'SylphxAI'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  # ========== Bump Configuration ==========
  mode:
    description: 'Bump mode: auto (default), release, version, or pr'
    default: 'auto'
  base-branch:
    description: 'Base branch for PR mode'
    default: 'main'

  # ========== Build Configuration ==========
  build-command:
    description: 'Command to build packages (runs before publish)'
    default: ''
  skip-build:
    description: 'Skip the build step'
    default: 'false'

  # ========== Runtime Configuration ==========
  bun-version:
    description: 'Bun version to use'
    default: 'latest'

  # ========== Release Configuration ==========
  dry-run:
    description: 'Preview changes without publishing'
    default: 'false'
  tag:
    description: 'Create git tags'
    default: 'true'
  changelog:
    description: 'Update CHANGELOG.md'
    default: 'true'
  github-release:
    description: 'Create GitHub release'
    default: 'true'

  # ========== Notification ==========
  slack-webhook:
    description: 'Slack webhook URL for notifications'
    default: ''

  # ========== Advanced Options ==========
  working-directory:
    description: 'Working directory for commands'
    default: '.'

  # ========== Required Secrets (passed as inputs) ==========
  npm-token:
    description: 'NPM authentication token'
    required: true
  github-token:
    description: 'GitHub token for creating releases and PRs'
    required: true

outputs:
  published:
    description: 'Whether packages were published'
    value: ${{ steps.bump.outputs.published }}
  version:
    description: 'The new version (for single package repos)'
    value: ${{ steps.bump.outputs.version }}
  versions:
    description: 'JSON object of package versions (for monorepos)'
    value: ${{ steps.bump.outputs.versions }}

runs:
  using: 'composite'
  steps:
    - name: Build (if configured)
      if: inputs.build-command != '' && inputs.skip-build != 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.build-command }}

    - name: Run Bump
      id: bump
      uses: SylphxAI/bump@v0
      with:
        mode: ${{ inputs.mode }}
        base-branch: ${{ inputs.base-branch }}
        dry-run: ${{ inputs.dry-run }}
        tag: ${{ inputs.tag }}
        changelog: ${{ inputs.changelog }}
        github-release: ${{ inputs.github-release }}
        working-directory: ${{ inputs.working-directory }}
        github-token: ${{ inputs.github-token }}
        npm-token: ${{ inputs.npm-token }}

    - name: Notify Slack on publish
      if: steps.bump.outputs.published == 'true' && inputs.slack-webhook != ''
      shell: bash
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        VERSION: ${{ steps.bump.outputs.version }}
        VERSIONS: ${{ steps.bump.outputs.versions }}
      run: |
        REPO="${{ github.repository }}"
        REPO_URL="https://github.com/$REPO"

        # Build message based on single package or monorepo
        if [ -n "$VERSION" ]; then
          # Single package
          PKG_NAME=$(jq -r .name package.json 2>/dev/null || echo "$REPO")
          MESSAGE="📦 *${PKG_NAME}* \`v${VERSION}\` published\n<${REPO_URL}/releases/tag/v${VERSION}|View Release>"
        elif [ -n "$VERSIONS" ] && [ "$VERSIONS" != "{}" ]; then
          # Monorepo - list all packages
          MESSAGE="📦 *Packages published*\n"
          for pkg in $(echo "$VERSIONS" | jq -r 'keys[]' 2>/dev/null); do
            ver=$(echo "$VERSIONS" | jq -r --arg p "$pkg" '.[$p]' 2>/dev/null)
            MESSAGE="${MESSAGE}• ${pkg}@${ver}\n"
          done
          MESSAGE="${MESSAGE}<${REPO_URL}|View Repository>"
        else
          MESSAGE="📦 Release published from *${REPO}*\n<${REPO_URL}|View Repository>"
        fi

        # Send to Slack
        curl -s -X POST "$SLACK_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "{\"text\": \"${MESSAGE}\"}"

    - name: Notify Slack on failure
      if: failure() && inputs.slack-webhook != ''
      shell: bash
      run: |
        WEBHOOK="${{ inputs.slack-webhook }}"
        REPO="${{ github.repository }}"
        RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        BRANCH="${{ github.ref_name }}"

        MESSAGE="❌ *Publish failed*\n"
        MESSAGE="${MESSAGE}Repository: ${REPO}\n"
        MESSAGE="${MESSAGE}Branch: ${BRANCH}\n"
        MESSAGE="${MESSAGE}<${RUN_URL}|View Workflow>"

        curl -s -X POST "$WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "{\"text\": \"${MESSAGE}\"}"
