name: 'Publish to NPM'
description: 'Publish packages to npm using bump with Slack notifications'
author: 'SylphxAI'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  npm-token:
    description: 'NPM authentication token'
    required: true
  github-token:
    description: 'GitHub token for creating releases and PRs'
    required: true
  mode:
    description: 'Bump mode: auto (default), release, version, or pr'
    default: 'auto'
  base-branch:
    description: 'Base branch for PR mode'
    default: 'main'
  dry-run:
    description: 'Preview changes without publishing'
    default: 'false'
  working-directory:
    description: 'Working directory'
    default: '.'
  slack-webhook:
    description: 'Slack webhook URL for notifications'
    default: ''

outputs:
  published:
    description: 'Whether packages were published'
    value: ${{ steps.bump.outputs.published }}
  version:
    description: 'The new version (single package)'
    value: ${{ steps.bump.outputs.version }}
  versions:
    description: 'JSON object of package versions (monorepo)'
    value: ${{ steps.bump.outputs.versions }}

runs:
  using: 'composite'
  steps:
    - name: Run Bump
      id: bump
      uses: SylphxAI/bump@v0
      with:
        mode: ${{ inputs.mode }}
        base-branch: ${{ inputs.base-branch }}
        dry-run: ${{ inputs.dry-run }}
        working-directory: ${{ inputs.working-directory }}
        github-token: ${{ inputs.github-token }}
        npm-token: ${{ inputs.npm-token }}

    - name: Notify Slack on publish
      if: steps.bump.outputs.published == 'true' && inputs.slack-webhook != ''
      shell: bash
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook }}
        VERSION: ${{ steps.bump.outputs.version }}
        VERSIONS: ${{ steps.bump.outputs.versions }}
      run: |
        REPO="${{ github.repository }}"
        REPO_URL="https://github.com/$REPO"

        if [ -n "$VERSION" ]; then
          PKG_NAME=$(jq -r .name package.json 2>/dev/null || echo "$REPO")
          MESSAGE="📦 *${PKG_NAME}* \`v${VERSION}\` published\n<${REPO_URL}/releases/tag/v${VERSION}|View Release>"
        elif [ -n "$VERSIONS" ] && [ "$VERSIONS" != "{}" ]; then
          MESSAGE="📦 *Packages published*\n"
          for pkg in $(echo "$VERSIONS" | jq -r 'keys[]' 2>/dev/null); do
            ver=$(echo "$VERSIONS" | jq -r --arg p "$pkg" '.[$p]' 2>/dev/null)
            MESSAGE="${MESSAGE}• ${pkg}@${ver}\n"
          done
          MESSAGE="${MESSAGE}<${REPO_URL}|View Repository>"
        else
          MESSAGE="📦 Release published from *${REPO}*\n<${REPO_URL}|View Repository>"
        fi

        curl -s -X POST "$SLACK_WEBHOOK" \
          -H "Content-Type: application/json" \
          -d "{\"text\": \"${MESSAGE}\"}"

    - name: Notify Slack on failure
      if: failure() && inputs.slack-webhook != ''
      shell: bash
      run: |
        curl -s -X POST "${{ inputs.slack-webhook }}" \
          -H "Content-Type: application/json" \
          -d "{\"text\": \"❌ *Publish failed*\nRepository: ${{ github.repository }}\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>\"}"
